### ISSUE TITLE
Transaction Support

### ISSUE THREAD

**Issue by whitehead1415** [twittner/cql-io#11]
How would you perform a lightweight transaction?

I am new to cassandra so please excuse my ignorance.

**Comment by twittner** [comment]
In theory one would just use `IF` clauses (e.g. `IF NOT EXISTS`) as part of regular query strings. However it does not work at the moment. The reason is that with "lightweight transactions" the result of a statement like `insert` varies and this does not fit at all the model of typed query strings as currently implement. I have to think about how best to support it.

**Comment by twittner** [comment]
I have released new versions of cql and cql-io to hackage with the changes we discussed [here](https://github.com/twittner/cql/pull/3) so I am closing this issue. Thanks again for bringing it up.
