### ISSUE TITLE
Prepared statements

### ISSUE THREAD

**Issue by rjmac** [twittner/cql-io#4]
I've implemented on [a branch of my fork](https://github.com/rjmac/cql-io/tree/prepared-queries) some prepared statement support for cql-io, adding a `prepare` function and changing the various "execute query" functions to take values whose types are instances of `QueryLike` instead of only `QueryString`s.  If you're interested in this, I can send a pull request, but I  thought I'd get your opinion on the approach first, since it does change the signatures (though not the use) of basically everything public in the `IO` package.

**Comment by twittner** [comment]
Thank you. I will have a look soon.

**Comment by twittner** [comment]
I began to implement prepared statements support on a [prepared-statements branch](https://github.com/twittner/cql-io/tree/prepared-statements). The current state of this branch has not been tested yet and may still undergo a couple more revisions. There are some details to consider, e.g.

1. Assumptions about the `QueryId` format.
2. The interplay between policies and transparent re-preparation.
3. Cluster-wide or single node preparation.
4. Batch statements.
5. Usage in application code.

(1) According to the native protocol spec, the query ID is "[...] global to the node on which the query has been prepared. It can be used on any connection to that node and this until the node is restarted (after which the query must be reprepared).". IIUC this would imply that the same query string could yield different query IDs on different nodes and this in turn would imply that a client can only execute against the very same node which was used for query preparation. That being said it seems to me after some cursory reading that at least the datastax driver assumes that for every query string, the prepare operation would return the same query ID regardless of the node. I feel somewhat uncomfortable having to rely on an implementation detail but I think the benefits are worth it.

(2) The client sends a request to a host selected by a [policy](https://github.com/twittner/cql-io/blob/prepared-statements/src/Database/CQL/IO/Cluster/Policies.hs#L38). Policies could be "random", or "round-robin" for example. Transparent (re-)preparation of queries can not just make two independent requests, since the first (prepare) may go to a different host than the second (execute).

(3) Depending on the scope of prepared query reuse, it may either be best to repare against the whole cluster or just against a single node. Since I can not anticipate what is best for everyone I chose to make it a configuration option ([prepareStrategy](https://github.com/twittner/cql-io/blob/prepared-statements/src/Database/CQL/IO/Settings.hs#L25-L28)).

(4) Since batch statements also support prepared statements, I added a small utiltiy monad [BatchM](https://github.com/twittner/cql-io/blob/prepared-statements/src/Database/CQL/IO/Batch.hs) to setup batches.

(5) Currently querystrings can be declared as top-level values in modules and I would like to support the same style for prepared queries. Obtaining a `QueryId` however is an effectful operation. The idea is thus to map a client-internal ID to the actual `QueryId`. The type [PrepQuery](https://github.com/twittner/cql-io/blob/prepared-statements/src/Database/CQL/IO/PrepQuery.hs) can be used for pure declarations and execution will transparently prepare as needed. The declaration is currently requiring a salt per `PrepQuery` value. I may switch to a different scheme instead. Finally, to abstract over `QueryString`s in the various query functions of `Database.CQL.IO` I introduced the `RunQ` type-class which corresponds roughly to your `QueryLike` type-class.

If you plan to make use of this functionality and discover any problems I would appreciate your feedback.

**Comment by rjmac** [comment]
I've converted my prepared-statement-using code to use this branch; it was very straightforward to do.  In writing my branch, (1) had bothered me too (I also looked at the official driver and the Cassandra source code -- the queryid is basically `md5(currentKeyspace ++ query)`) and it would be nice to have a documented guarantee that query IDs are predictable, though at least with the Java driver assuming the same thing it'll require a major protocol version bump to change it.  Having "create a prepared statement" be a MonadClient action had also bothered me.  I am mildly nervous about the approach taken in PrepQuery.  It seems like using a non-cryptographic hash of the query text as a key risks rare but hard-to-diagnose bugs.

**Comment by twittner** [comment]
Thank you for your quick reply. Regarding the `PrepQueryId` I fully agree with your reservations. I was toying with the idea to let applications enumerate the queries in order to avoid collisions, but it may not be practical with a large number of queries. An alternative—as you mentioned—would be a cryptographic hash function and given the fact that Cassandra itself seems to be content using only MD5 it may work just fine. Regardless it may still be a good idea throw an error in case a collision is detected. Cf. https://github.com/twittner/cql-io/commit/0facc558806f89e9035b6b3b0e6ca8911d46cc88 for details

**Comment by rjmac** [comment]
Been using this off and on over the last week, and it works quite well indeed.

**Comment by twittner** [comment]
Thanks. I rebased and merged this into `develop`.
